# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

discretize_vectors_cpp <- function(x, y, dims, x_range, y_range) {
    .Call(`_attractor_discretize_vectors_cpp`, x, y, dims, x_range, y_range)
}

discretize_cpp <- function(data, dims, x_range, y_range) {
    .Call(`_attractor_discretize_cpp`, data, dims, x_range, y_range)
}

strange_attractor_cpp <- function(a, n, x0, y0, display_progress = TRUE) {
    .Call(`_attractor_strange_attractor_cpp`, a, n, x0, y0, display_progress)
}

quantile_cpp <- function(x, q) {
    .Call(`_attractor_quantile_cpp`, x, q)
}

strange_attractor_discretized_cpp <- function(a, n, x0, y0, dims, qs, display_progress = TRUE, n_discretize = 1e5L) {
    .Call(`_attractor_strange_attractor_discretized_cpp`, a, n, x0, y0, dims, qs, display_progress, n_discretize)
}

